
####################################################################################
# Generated by Vivado 2018.3 built on 'Thu Dec  6 23:36:41 MST 2018' by 'xbuild'
# Command Used: write_xdc Sources/xdc/fplan_zed.xdc -force
####################################################################################


# User Generated miscellaneous constraints 

set_property HD.RECONFIGURABLE true [get_cells system_i/math_0/inst/math_v1_0_S_AXI_inst/rp_instance]

# User Generated physical constraints 

create_pblock pblock_rp_instance
add_cells_to_pblock [get_pblocks pblock_rp_instance] [get_cells -quiet [list system_i/math_0/inst/math_v1_0_S_AXI_inst/rp_instance]]
resize_pblock [get_pblocks pblock_rp_instance] -add {SLICE_X34Y109:SLICE_X39Y123}
resize_pblock [get_pblocks pblock_rp_instance] -add {DSP48_X2Y44:DSP48_X2Y47}

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
