
####################################################################################
# Generated by Vivado 2018.3 built on 'Thu Dec  6 23:36:41 MST 2018' by 'xbuild'
# Command Used: write_xdc Sources/xdc/fplan_zturn.xdc
####################################################################################


####################################################################################
# Constraints from file : 'xpm_cdc_async_rst.tcl'
####################################################################################

# Scoped constraints for xpm_cdc_async_rst
current_instance top_i/char_fifo_i/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.gnsckt_wrst.gic_rst.rst_rd_reg2_inst
set_false_path -through [get_ports -scoped_to_current_instance src_arst] -to [all_registers]


# Scoped constraints for xpm_cdc_async_rst
current_instance -quiet
current_instance top_i/char_fifo_i/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.gnsckt_wrst.rst_wr_reg2_inst
set_false_path -through [get_ports -scoped_to_current_instance src_arst] -to [all_registers]



####################################################################################
# Constraints from file : 'xpm_cdc_gray.tcl'
####################################################################################

# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance top_i/char_fifo_i/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_cdc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 1000.000
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 1000.000



# Scoped constraints for xpm_cdc_gray




current_instance -quiet
current_instance top_i/char_fifo_i/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_cdc_inst
set_max_delay -datapath_only -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 1000.000
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 1000.000




####################################################################################
# Constraints from file : 'xpm_cdc_single.tcl'
####################################################################################

# Scoped constraints for xpm_cdc_single

current_instance -quiet
current_instance top_i/char_fifo_i/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.gnsckt_wrst.gic_rst.xpm_cdc_single_inst_rrst_wr
set_false_path -to [get_cells {syncstages_ff_reg[0]}]


# Scoped constraints for xpm_cdc_single

current_instance -quiet
current_instance top_i/char_fifo_i/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.gnsckt_wrst.gic_rst.xpm_cdc_single_inst_wrst_rd
set_false_path -to [get_cells {syncstages_ff_reg[0]}]



# User Generated miscellaneous constraints 

current_instance -quiet
set_property HD.RECONFIGURABLE true [get_cells top_i/reconfig_addsub]
set_property HD.RECONFIGURABLE true [get_cells top_i/reconfig_leds]

# User Generated physical constraints 

create_pblock pblock_reconfig_addsub
add_cells_to_pblock [get_pblocks pblock_reconfig_addsub] [get_cells -quiet [list top_i/reconfig_addsub]]
resize_pblock [get_pblocks pblock_reconfig_addsub] -add {SLICE_X24Y36:SLICE_X27Y39}
create_pblock pblock_reconfig_leds
add_cells_to_pblock [get_pblocks pblock_reconfig_leds] [get_cells -quiet [list top_i/reconfig_leds]]
resize_pblock [get_pblocks pblock_reconfig_leds] -add {SLICE_X16Y20:SLICE_X19Y24}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_reconfig_leds]
set_property SNAPPING_MODE ON [get_pblocks pblock_reconfig_leds]

# User Generated miscellaneous constraints 


####################################################################################
# Constraints from file : 'xpm_cdc_gray.tcl'
####################################################################################

current_instance top_i/char_fifo_i/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_cdc_inst
create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Apr  9 15:50:28 GMT 2021"
current_instance -quiet
current_instance top_i/char_fifo_i/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_cdc_inst
create_waiver -type CDC -id {CDC-6} -user "xpm_cdc" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -internal -from [get_pins -quiet src_gray_ff_reg*/C] -to [get_pins -quiet dest_graysync_ff_reg*/D] -timestamp "Fri Apr  9 15:50:28 GMT 2021"

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
