
####################################################################################
# Generated by Vivado 2018.3 built on 'Thu Dec  6 23:36:41 MST 2018' by 'xbuild'
# Command Used: write_xdc Sources/xdc/mytestfplan_zed.xdc
####################################################################################


# User Generated miscellaneous constraints 

set_property HD.RECONFIGURABLE true [get_cells top_i/reconfig_addsub]
set_property HD.RECONFIGURABLE true [get_cells top_i/reconfig_leds]

# User Generated physical constraints 

create_pblock pblock_reconfig_addsub
add_cells_to_pblock [get_pblocks pblock_reconfig_addsub] [get_cells -quiet [list top_i/reconfig_addsub]]
resize_pblock [get_pblocks pblock_reconfig_addsub] -add {SLICE_X24Y36:SLICE_X27Y39}
create_pblock pblock_reconfig_leds
add_cells_to_pblock [get_pblocks pblock_reconfig_leds] [get_cells -quiet [list top_i/reconfig_leds]]
resize_pblock [get_pblocks pblock_reconfig_leds] -add {SLICE_X16Y20:SLICE_X19Y24}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_reconfig_leds]
set_property SNAPPING_MODE ON [get_pblocks pblock_reconfig_leds]

# User Generated miscellaneous constraints 


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
