#ZYBO
set_property PACKAGE_PIN M14 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property PACKAGE_PIN M15 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property PACKAGE_PIN G14 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property PACKAGE_PIN D18 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]

#BTN[0]
set_property PACKAGE_PIN R18 [get_ports button_start]
set_property IOSTANDARD LVCMOS33 [get_ports button_start]
#BTN[1]
set_property PACKAGE_PIN P16 [get_ports button_stop]
set_property IOSTANDARD LVCMOS33 [get_ports button_stop]
#BTN[2]
set_property PACKAGE_PIN V16 [get_ports led_reset]
set_property IOSTANDARD LVCMOS33 [get_ports led_reset]
