set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_reset}]
set_property IOSTANDARD LVCMOS33 [get_ports {button_stop}]
set_property IOSTANDARD LVCMOS33 [get_ports {button_start}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN Y16 [get_ports {led[0]}]
set_property PACKAGE_PIN Y17 [get_ports {led[1]}]
set_property PACKAGE_PIN R14 [get_ports {led[2]}]
set_property PACKAGE_PIN T19 [get_ports {button_start}]
set_property PACKAGE_PIN G14 [get_ports {button_stop}]
set_property PACKAGE_PIN J15 [get_ports {led_reset}]
set_property PACKAGE_PIN P18 [get_ports {led[3]}]

